const { createApp, nextTick, markRaw } = Vue;

const chinaRegionRows = [
  ['北京市','北京',39.9042,116.4074],['天津市','天津',39.0851,117.1994],['河北省','石家庄',38.0428,114.5149],['山西省','太原',37.8706,112.5489],
  ['内蒙古自治区','呼和浩特',40.8426,111.7492],['辽宁省','沈阳',41.8057,123.4315],['吉林省','长春',43.8171,125.3235],['黑龙江省','哈尔滨',45.8038,126.5349],
  ['上海市','上海',31.2304,121.4737],['江苏省','南京',32.0603,118.7969],['浙江省','杭州',30.2741,120.1551],['安徽省','合肥',31.8206,117.2272],
  ['福建省','福州',26.0745,119.2965],['江西省','南昌',28.682,115.8579],['山东省','济南',36.6512,117.1201],['河南省','郑州',34.7466,113.6254],
  ['湖北省','武汉',30.5928,114.3055],['湖南省','长沙',28.2282,112.9388],['广东省','广州',23.1291,113.2644],['广西壮族自治区','南宁',22.817,108.3665],
  ['海南省','海口',20.044,110.1999],['重庆市','重庆',29.563,106.5516],['四川省','成都',30.5728,104.0668],['贵州省','贵阳',26.647,106.6302],
  ['云南省','昆明',25.0389,102.7183],['西藏自治区','拉萨',29.6525,91.1721],['陕西省','西安',34.3416,108.9398],['甘肃省','兰州',36.0611,103.8343],
  ['青海省','西宁',36.6171,101.7782],['宁夏回族自治区','银川',38.4872,106.2309],['新疆维吾尔自治区','乌鲁木齐',43.8256,87.6168],
  ['香港特别行政区','香港',22.3193,114.1694],['澳门特别行政区','澳门',22.1987,113.5439],['台湾省','台北',25.033,121.5654]
];
const chinaRegionLookup = new Map();
chinaRegionRows.forEach((row,index)=>{
  const [name,capital,latitude,longitude]=row;
  const item={id:`CN-ADM1-${index}`,name,admin1:name,admin2:capital,country:'中国',country_code:'CN',latitude,longitude,feature_code:'ADM1',regionLabel:`行政中心 ${capital} 代表点`};
  const short=name.replace(/特别行政区$|维吾尔自治区$|壮族自治区$|回族自治区$|自治区$|省$|市$/,'');
  [name,short,`中国${name}`,`中国${short}`].forEach(alias=>chinaRegionLookup.set(alias,item));
  if(name==='台湾省')['台湾','臺灣','臺灣省','中国台湾','中國臺灣'].forEach(alias=>chinaRegionLookup.set(alias,item));
});

createApp({
  data(){return{
    lang:localStorage.getItem('yidan-lang')||'zh',darkMode:localStorage.getItem('yidan-dark')==='true',scrolled:false,showLogin:false,showProfile:false,showMyTrips:false,showMobileMenu:false,myTripTab:'cities',loading:false,toast:'',query:'',suggestions:[],selectedCity:null,planningRequested:false,weather:null,weatherError:'',weatherRequestId:0,travelDate:new Date().toISOString().slice(0,10),today:new Date().toISOString().slice(0,10),user:null,authMode:'login',authLoading:false,authReady:false,authError:'',authMessage:'',showPassword:false,showConfirmPassword:false,supabaseClient:null,authSubscription:null,loginForm:{name:'',email:'',password:'',confirmPassword:''},savedCities:[],savedTrips:[],cloudLoading:false,cloudError:'',savingTrip:false,pendingTripItinerary:null,plannerView:'list',routeMap:null,mapRenderTimer:null,budget:Number(localStorage.getItem('yidan-budget'))||3800,tripDays:Number(localStorage.getItem('yidan-trip-days'))||3,travelInterests:(()=>{try{return JSON.parse(localStorage.getItem('yidan-interests')||'["culture","food"]')}catch{return['culture','food']}})(),
    quickCities:[
      {id:1816670,name:'北京',admin1:'北京',country:'中国',latitude:39.9075,longitude:116.39723,label:{zh:'北京',en:'Beijing'}},
      {id:1808926,name:'杭州',admin1:'浙江',country:'中国',latitude:30.29365,longitude:120.16142,label:{zh:'杭州',en:'Hangzhou'}},
      {id:1850147,name:'東京',admin1:'東京都',country:'日本',latitude:35.6895,longitude:139.69171,label:{zh:'东京',en:'Tokyo'}},
      {id:2988507,name:'Paris',admin1:'Île-de-France',country:'France',latitude:48.85341,longitude:2.3488,label:{zh:'巴黎',en:'Paris'}}
    ],
    interestOptions:[
      {id:'nature',icon:'🌿',zh:'自然',en:'Nature'},{id:'culture',icon:'🏛️',zh:'人文',en:'Culture'},{id:'food',icon:'🍜',zh:'美食',en:'Food'},
      {id:'photo',icon:'📷',zh:'打卡',en:'Photo'},{id:'fun',icon:'🎡',zh:'娱乐',en:'Fun'},{id:'slow',icon:'🧘',zh:'慢节奏',en:'Slow'}
    ],
    activeWallpaper:0,previousWallpaper:null,wallpaperTimer:null,wallpaperCleanupTimer:null,
    wallpapers:[
      {src:'assets/spotlight-alps.png',zh:'瑞士阿尔卑斯山',en:'Swiss Alps',countryZh:'瑞士',countryEn:'Switzerland',descZh:'晨光掠过雪峰与高山湖泊',descEn:'First light across peaks and alpine water'},
      {src:'assets/spotlight-iceland.png',zh:'维克黑沙滩',en:'Vík Coast',countryZh:'冰岛',countryEn:'Iceland',descZh:'极光落在火山海岸与瀑布之上',descEn:'Aurora over volcanic shores and waterfalls'},
      {src:'assets/spotlight-fuji.png',zh:'河口湖与富士山',en:'Lake Kawaguchi',countryZh:'日本',countryEn:'Japan',descZh:'樱花季清晨，湖面映照富士山',descEn:'Fuji reflected in a quiet spring morning'},
      {src:'assets/spotlight-lofoten.png',zh:'罗弗敦群岛',en:'Lofoten Islands',countryZh:'挪威',countryEn:'Norway',descZh:'峡湾、渔村与雨后的北境阳光',descEn:'Fjords and fishing villages after rain'}
    ],
    attractions:[],restaurants:[],hotels:[],attractionsLoading:false,supportPlacesLoading:false,supportPlacesPromise:null,planError:'',activeDay:1,itinerary:[],
    destinations:[
      {search:'Dali',emoji:'🏔️',gradient:'linear-gradient(145deg,#b7d5cd,#56877c)',tagZh:'山野治愈',tagEn:'Mountain retreat',zh:'云南 · 大理',en:'Dali · Yunnan',descZh:'苍山洱海之间，寻找风、花与慢生活。',descEn:'Find slow living between Cangshan and Erhai.'},
      {search:'Kyoto',emoji:'⛩️',gradient:'linear-gradient(145deg,#e2c7a0,#b6754d)',tagZh:'文化漫游',tagEn:'Culture journey',zh:'日本 · 京都',en:'Kyoto · Japan',descZh:'穿过古寺与町屋，遇见四季流转。',descEn:'Walk through temples and timeless seasons.'},
      {search:'Reykjavik',emoji:'🌌',gradient:'linear-gradient(145deg,#8496ad,#283f51)',tagZh:'极境探索',tagEn:'Wild escape',zh:'冰岛 · 雷克雅未克',en:'Reykjavik · Iceland',descZh:'火山、冰川与极光构成的梦幻旅程。',descEn:'Volcanoes, glaciers and northern lights.'}
    ],
    i18n:{
      zh:{brand:'亿蛋大帝旅游宝',discover:'探索目的地',planner:'行程规划',inspiration:'旅行灵感',theme:'切换主题',login:'登录',logout:'退出登录',eyebrow:'为每一次出发，找到更好的答案',heroTitle1:'世界很大，',heroTitle2:'出发正好。',heroSub:'输入目的地、游玩天数与预算，我们会结合天气为你生成可执行的旅行计划。',where:'目的地',cityPlaceholder:'搜索全球城市，如：东京、伦敦',when:'出发日期',explore:'开始探索',searching:'正在寻找',popular:'热门搜索',scroll:'向下探索',liveWeather:'全球天气预报',ready:'这次出发，天气如何？',save:'收藏城市',saved:'已收藏',feels:'体感',high:'最高',low:'最低',humidity:'湿度',wind:'风速',rain:'降水',smartAdvice:'智能出行建议',pack:'建议携带',tripPlanner:'旅行社式完整路线',planTitle:'从早餐后出发，到晚上安心住下。',planSub:'每天包含顺路景点、真实餐厅、晚餐和住宿建议；天气决定室内外节奏，预算决定餐饮与住宿档位。',feature1:'景点按距离顺路组合',feature2:'真实餐厅与住宿推荐',feature3:'每天完整费用估算',myTrip:'为你生成的完整路线',dreamTrip:'选择城市后生成',activities:'项完整安排',addActivity:'按当前预算重新生成',estimated:'旅行总预算',placesTitle:'下一站，去哪里？',placesSub:'为你挑选三种截然不同的旅行心情。',footer:'让每一次出发，都从容而值得。',welcome:'欢迎回来，旅行家',loginSub:'登录后即可收藏目的地与保存偏好。',name:'你的昵称',namePh:'例如：亿蛋大帝',email:'邮箱',startJourney:'开启旅程',privacy:'演示模式：信息仅保存在你的浏览器中',chooseCity:'请选择准确的城市',loadFailed:'天气数据加载失败，请重试',retry:'重新加载',dataTime:'数据时刻',rawData:'查看 API 原始数据',forecastNote:'Open-Meteo Best Match 预报模型（不是气象站实测）',findingPlaces:'正在组合景点、餐厅与住宿…',planFailed:'当地路线数据暂时加载失败，请重试',openMap:'地图',placeSource:'景点、餐厅和住宿来自 OpenStreetMap；天气来自 Open-Meteo；费用均为估算',tripLength:'游玩时间',days:'天',totalBudget:'总预算',perDay:'每天约',ticketEstimate:'已规划费用估算',flexibleReserve:'机动预算',estimatedCost:'估算',budgetTight:'预算较紧：优先免费景点、平价餐饮与青旅',budgetBalanced:'预算适中：当地餐厅与舒适住宿均衡搭配',budgetRelaxed:'预算充足：加入特色餐厅与品质酒店建议',morningRoute:'上午路线',lunch:'午餐推荐',afternoonRoute:'下午路线',dinner:'晚餐推荐',stay:'住宿建议',routeLogic:'顺路逻辑',completeDays:'天完整路线'},
      en:{brand:'Yidan Travel',discover:'Discover',planner:'Trip Planner',inspiration:'Inspiration',theme:'Toggle theme',login:'Sign in',logout:'Sign out',eyebrow:'A better answer for every departure',heroTitle1:'The world is wide.',heroTitle2:'Go now.',heroSub:'Enter a destination, trip length and budget. We turn the forecast into a practical itinerary.',where:'Destination',cityPlaceholder:'Search anywhere, e.g. Tokyo or London',when:'Departure',explore:'Explore',searching:'Searching',popular:'Trending',scroll:'Explore more',liveWeather:'Global weather forecast',ready:'How is the weather for this trip?',save:'Save city',saved:'Saved',feels:'Feels',high:'High',low:'Low',humidity:'Humidity',wind:'Wind',rain:'Rain',smartAdvice:'Smart travel advice',pack:'Pack this',tripPlanner:'Travel-agency style route',planTitle:'From the first stop to a good night’s stay.',planSub:'Every day combines nearby sights, real restaurants, dinner and lodging; weather sets the rhythm, while budget sets dining and stay tiers.',feature1:'Nearby sights grouped into routes',feature2:'Real dining and lodging picks',feature3:'Complete daily cost estimate',myTrip:'Your complete route',dreamTrip:'Choose a city to generate',activities:'complete stops',addActivity:'Regenerate for this budget',estimated:'Total trip budget',placesTitle:'Where to next?',placesSub:'Three completely different moods, handpicked for you.',footer:'Make every departure effortless and worthwhile.',welcome:'Welcome back, traveler',loginSub:'Sign in to save destinations and preferences.',name:'Your name',namePh:'e.g. Yidan',email:'Email',startJourney:'Start the journey',privacy:'Demo mode: your data stays in this browser',chooseCity:'Choose the exact city',loadFailed:'Weather data failed to load. Please retry.',retry:'Try again',dataTime:'Data time',rawData:'View raw API data',forecastNote:'Open-Meteo Best Match forecast model (not a station observation)',findingPlaces:'Combining sights, restaurants and lodging…',planFailed:'Local route data failed to load. Please retry.',openMap:'Map',placeSource:'Sights, dining and lodging from OpenStreetMap; weather from Open-Meteo; all costs are estimates',tripLength:'Trip length',days:'days',totalBudget:'Total budget',perDay:'Per day',ticketEstimate:'Planned estimate',flexibleReserve:'Flexible reserve',estimatedCost:'Est.',budgetTight:'Tight budget: prioritizing free sights, affordable dining and hostels',budgetBalanced:'Balanced budget: local restaurants and comfortable stays',budgetRelaxed:'Flexible budget: adding distinctive dining and quality hotels',morningRoute:'Morning route',lunch:'Lunch',afternoonRoute:'Afternoon route',dinner:'Dinner',stay:'Where to stay',routeLogic:'Route logic',completeDays:'complete days'}
    }
  }},
  computed:{
    isSaved(){return this.selectedCity&&this.savedCities.some(c=>this.cityKey(c)===this.cityKey(this.selectedCity))},
    travelWeatherIndex(){if(!this.weather)return 0;const diff=Math.round((new Date(this.travelDate+'T12:00:00')-new Date(this.today+'T12:00:00'))/86400000);return Math.max(0,Math.min(diff,(this.weather.daily?.time?.length||1)-1))},
    maxTravelDate(){const d=new Date(this.today+'T12:00:00');d.setDate(d.getDate()+Math.max(0,16-this.tripDays));return d.toISOString().slice(0,10)},
    dailyBudget(){return Math.round(Number(this.budget)/Number(this.tripDays||1))},
    planLoading(){return this.attractionsLoading||this.supportPlacesLoading},
    itineraryCost(){return this.itinerary.reduce((sum,item)=>sum+(item.estimatedCost||0),0)},
    reserveBudget(){return Math.max(0,Number(this.budget)-this.itineraryCost)},
    budgetGap(){return Math.max(0,this.itineraryCost-Number(this.budget))},
    minimumSuggestedBudget(){return this.tripDays*250},
    activeDayItems(){return this.itinerary.filter(item=>item.day===this.activeDay)},
    activeDayCost(){return this.activeDayItems.reduce((sum,item)=>sum+(item.estimatedCost||0),0)},
    activeDayReasons(){
      if(!this.weather||!this.activeDayItems.length)return[];
      const weatherIndex=Math.min(this.travelWeatherIndex+this.activeDay-1,this.weather.daily.time.length-1),rain=this.weather.daily.precipitation_probability_max[weatherIndex]||0,max=Math.round(this.weather.daily.temperature_2m_max[weatherIndex]);
      const routeItems=this.activeDayItems.filter(item=>item.points?.length>1),routeDistance=routeItems.reduce((sum,item)=>sum+this.distanceKm(item.points[0],item.points[1]),0).toFixed(1),interests=this.interestOptions.filter(option=>this.travelInterests.includes(option.id)).map(option=>option[this.lang]).join('、');
      return this.lang==='zh'?
        [{icon:rain>=50?'umbrella':'sun',text:rain>=50?`当天降雨概率 ${rain}%，优先安排室内景点并预留避雨时间。`:(max>=30?`最高 ${max}°，户外景点集中在早晚，避开正午高温。`:`最高 ${max}°、降雨概率 ${rain}%，适合步行串联景点。`)},{icon:'route',text:`当日主要景点的串联距离约 ${routeDistance} km，优先选择附近的下一站，减少折返。`},{icon:'wallet-cards',text:`日均预算约 ¥${this.dailyBudget.toLocaleString()}，已匹配${this.dailyBudget<500?'经济型':this.dailyBudget<1500?'舒适型':'品质型'}餐饮与住宿。`},{icon:'sparkles',text:`兴趣偏好：${interests||'综合体验'}，同类景点在候选排序中获得更高权重。`}]:
        [{icon:rain>=50?'umbrella':'sun',text:rain>=50?`${rain}% rain chance: indoor stops lead the route with buffer time.`:(max>=30?`High ${max}°: outdoor stops shift toward morning and evening.`:`High ${max}° with ${rain}% rain: suitable for a connected walking route.`)},{icon:'route',text:`Key sights are linked across about ${routeDistance} km, favoring the nearest useful next stop.`},{icon:'wallet-cards',text:`About ¥${this.dailyBudget.toLocaleString()} per day sets the dining and lodging tier.`},{icon:'sparkles',text:`Interests: ${interests||'balanced mix'}; matching places receive a higher ranking.`}];
    },
    activeDayRoutePoints(){const points=[];this.activeDayItems.forEach(item=>(item.points||[]).forEach(point=>{if(!points.some(existing=>existing.name===point.name&&existing.lat===point.lat&&existing.lon===point.lon))points.push({...point,type:item.type,time:item.time})}));return points},
    currentTripTitle(){if(!this.selectedCity)return'';return this.lang==='zh'?`${this.selectedCity.name} ${this.tripDays}日游`:`${this.selectedCity.name} · ${this.tripDays} days`},
    passwordScore(){const p=this.loginForm.password||'';return [p.length>=8,/[a-z]/i.test(p),/\d/.test(p),/[^a-z\d]/i.test(p)].filter(Boolean).length},
    passwordStrengthText(){if(!this.loginForm.password)return'';if(this.passwordScore<=1)return this.lang==='zh'?'较弱':'Weak';if(this.passwordScore<=3)return this.lang==='zh'?'安全':'Secure';return this.lang==='zh'?'很强':'Strong'},
    budgetAdvice(){if(this.budgetGap>0)return this.lang==='zh'?`当前完整路线预计 ¥${this.itineraryCost.toLocaleString()}，比预算高约 ¥${this.budgetGap.toLocaleString()}；可提高预算或按当前预算重新生成`:`This complete route is about ¥${this.itineraryCost.toLocaleString()}, roughly ¥${this.budgetGap.toLocaleString()} over budget; raise the budget or regenerate`;if(Number(this.budget)<this.minimumSuggestedBudget)return this.lang==='zh'?`${this.tripDays} 天建议至少准备 ¥${this.minimumSuggestedBudget.toLocaleString()}`:`At least ¥${this.minimumSuggestedBudget.toLocaleString()} is suggested for ${this.tripDays} days`;return this.dailyBudget<500?this.t('budgetTight'):this.dailyBudget<1500?this.t('budgetBalanced'):this.t('budgetRelaxed')},
    smartAdvice(){if(!this.weather)return{title:'',text:'',items:[]};const max=this.weather.daily.temperature_2m_max[0],rain=this.weather.daily.precipitation_probability_max[0],wind=this.weather.current.wind_speed_10m;if(this.lang==='zh'){if(rain>=60)return{title:'把雨也变成旅行的一部分',text:'今天降水概率较高，优先安排博物馆、咖啡馆与室内景点，雨歇时再去城市漫步。',items:['折叠伞','防水鞋','轻薄外套']};if(max>=30)return{title:'避开正午，拥抱清晨与傍晚',text:'天气偏热，建议把户外活动放在早晚，午后留给室内体验，并及时补水。',items:['防晒霜','水杯','遮阳帽']};if(max<=10)return{title:'穿暖一点，慢慢探索',text:'气温较低，分层穿搭会更舒适。选择温暖的餐厅作为途中停靠点。',items:['保暖外套','围巾','润唇膏']};return{title:'很适合步行探索的一天',text:`气温舒适${wind>25?'、风力稍大':'、降水风险较低'}，推荐安排城市漫步、地标打卡和一顿户外晚餐。`,items:['舒适鞋','充电宝','薄外套']}}else{if(rain>=60)return{title:'Make rain part of the journey',text:'Rain is likely. Prioritize museums and cafés, then explore outside between showers.',items:['Umbrella','Waterproof shoes','Light jacket']};if(max>=30)return{title:'Own the morning and evening',text:'It will be hot. Plan outdoor time early or late and stay hydrated.',items:['Sunscreen','Water bottle','Sun hat']};if(max<=10)return{title:'Layer up and take it slow',text:'Cool conditions call for layers and warm café stops along the way.',items:['Warm coat','Scarf','Lip balm']};return{title:'A wonderful day to explore on foot',text:'Comfortable temperatures make today great for city walks, landmarks and dinner outdoors.',items:['Walking shoes','Power bank','Light jacket']}}
    }
  },
  watch:{darkMode(v){localStorage.setItem('yidan-dark',v);this.refreshIcons()},lang(v){localStorage.setItem('yidan-lang',v);document.documentElement.lang=v==='zh'?'zh-CN':'en';this.refreshIcons();this.scheduleRouteMap()},weather(){this.refreshIcons()},showLogin(){this.refreshIcons()},showProfile(){this.refreshIcons()},showMyTrips(){this.refreshIcons()},showMobileMenu(){this.refreshIcons()},activeDay(){this.scheduleRouteMap()},plannerView(){this.scheduleRouteMap()},travelInterests:{deep:true,handler(v){localStorage.setItem('yidan-interests',JSON.stringify(v));if(this.planningRequested&&this.attractions.length)this.generateItinerary()}},itinerary:{deep:true,handler(v){if(this.selectedCity)localStorage.setItem(`yidan-itinerary-${this.selectedCity.id}`,JSON.stringify(v));this.scheduleRouteMap()}}},
  mounted(){window.addEventListener('scroll',()=>this.scrolled=window.scrollY>30);this.refreshIcons();this.initAuth();this.startWallpaperRotation();const params=new URLSearchParams(location.search),sharedCity=params.get('city'),sharedPlan=Boolean(params.get('date')||params.get('days')||params.get('budget')),lastCity=(()=>{try{return JSON.parse(localStorage.getItem('yidan-last-city')||'null')}catch{return null}})();if(params.get('date'))this.travelDate=params.get('date');if(params.get('days'))this.tripDays=Math.max(1,Math.min(7,Number(params.get('days'))||3));if(params.get('budget'))this.budget=Math.max(500,Math.min(30000,Number(params.get('budget'))||3800));setTimeout(()=>{if(sharedCity)this.quickSearch(sharedCity,false,sharedPlan);else if(lastCity)this.selectCity(lastCity,false)},300)},
  beforeUnmount(){this.authSubscription?.unsubscribe();clearInterval(this.wallpaperTimer);clearTimeout(this.wallpaperCleanupTimer);clearTimeout(this.mapRenderTimer);this.routeMap?.remove()},
  methods:{
    t(k){return this.i18n[this.lang][k]||k},refreshIcons(){},toggleLang(){this.lang=this.lang==='zh'?'en':'zh'},goHome(){window.scrollTo({top:0,behavior:'smooth'})},
    preloadWallpaper(index){const image=new Image();image.src=this.wallpapers[index].src},
    startWallpaperRotation(){clearInterval(this.wallpaperTimer);this.preloadWallpaper(this.activeWallpaper);this.preloadWallpaper((this.activeWallpaper+1)%this.wallpapers.length);this.wallpaperTimer=setInterval(()=>this.changeWallpaper(1,false),8000)},
    changeWallpaper(direction=1,resetTimer=true){const next=(this.activeWallpaper+direction+this.wallpapers.length)%this.wallpapers.length;if(next===this.activeWallpaper)return;this.previousWallpaper=this.activeWallpaper;this.activeWallpaper=next;this.preloadWallpaper((next+1)%this.wallpapers.length);clearTimeout(this.wallpaperCleanupTimer);this.wallpaperCleanupTimer=setTimeout(()=>this.previousWallpaper=null,1700);if(resetTimer)this.startWallpaperRotation()},
    selectWallpaper(index){if(index===this.activeWallpaper)return;this.previousWallpaper=this.activeWallpaper;this.activeWallpaper=index;this.preloadWallpaper((index+1)%this.wallpapers.length);clearTimeout(this.wallpaperCleanupTimer);this.wallpaperCleanupTimer=setTimeout(()=>this.previousWallpaper=null,1700);this.startWallpaperRotation()},
    normalizeLocation(v){return String(v||'').trim().replace(/\s+/g,'').replace(/^中华人民共和国|^中國|^中国/,'')},resolveKnownRegion(v){const key=this.normalizeLocation(v);return chinaRegionLookup.get(key)||chinaRegionLookup.get(`中国${key}`)||null},
    resolveGlobalCityQuery(v){const key=this.normalizeLocation(v).toLocaleLowerCase(),aliases={东京:'Tokyo',東京:'Tokyo',tokyo:'Tokyo',巴黎:'Paris',paris:'Paris',伦敦:'London',倫敦:'London',london:'London',纽约:'New York',紐約:'New York',newyork:'New York',首尔:'Seoul',首爾:'Seoul',seoul:'Seoul',京都:'Kyoto',kyoto:'Kyoto',大阪:'Osaka',osaka:'Osaka',曼谷:'Bangkok',bangkok:'Bangkok',新加坡:'Singapore',singapore:'Singapore',悉尼:'Sydney',雪梨:'Sydney',sydney:'Sydney',罗马:'Rome',羅馬:'Rome',rome:'Rome',巴塞罗那:'Barcelona',巴塞羅那:'Barcelona',barcelona:'Barcelona',迪拜:'Dubai',杜拜:'Dubai',dubai:'Dubai',雷克雅未克:'Reykjavik',reykjavik:'Reykjavik'};return aliases[key]||null},
    async searchCity(){this.planningRequested=false;if(this.query.trim().length<2){this.notify(this.lang==='zh'?'请输入至少两个字符':'Enter at least 2 characters');return}const knownRegion=this.resolveKnownRegion(this.query);if(knownRegion){this.suggestions=[];await this.selectCity({...knownRegion},false);return}const globalQuery=this.resolveGlobalCityQuery(this.query);if(globalQuery){this.suggestions=[];await this.quickSearch(globalQuery,false);return}this.loading=true;this.weatherError='';try{const rawQuery=this.query.trim(),url=`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(rawQuery)}&count=12&language=${this.lang}&format=json`;const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error();const data=await res.json(),normalized=this.normalizeLocation(rawQuery);const seen=new Set();this.suggestions=(data.results||[]).filter(city=>{const key=`${city.name}|${city.country}|${city.admin1||''}|${city.admin2||''}`.toLocaleLowerCase();if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>{const ae=this.normalizeLocation(a.name)===normalized?1:0,be=this.normalizeLocation(b.name)===normalized?1:0;if(ae!==be)return be-ae;return(b.population||0)-(a.population||0)}).slice(0,8);if(this.suggestions.length===1)await this.selectCity(this.suggestions[0],false);else if(this.suggestions.length>1)this.notify(this.t('chooseCity'));else this.notify(this.lang==='zh'?'没有找到这个城市，请换个关键词':'No city found. Try another keyword.')}catch(e){this.weatherError=this.lang==='zh'?'全球城市搜索暂时不可用，请重试':'Global city search is temporarily unavailable';this.notify(this.weatherError)}finally{this.loading=false;this.refreshIcons()}},
    async selectCity(city,shouldScroll=false){const requestId=++this.weatherRequestId;this.selectedCity=city;this.query=city.name;this.suggestions=[];this.weather=null;this.weatherError='';this.itinerary=[];this.attractions=[];this.restaurants=[];this.hotels=[];this.activeDay=1;this.planError='';this.loading=true;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const p='current=temperature_2m,relative_humidity_2m,apparent_temperature,is_day,weather_code,wind_speed_10m&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max';const url=`https://api.open-meteo.com/v1/forecast?latitude=${city.latitude}&longitude=${city.longitude}&${p}&timezone=auto&forecast_days=16`;const res=await fetch(url,{cache:'no-store',signal:controller.signal});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();if(requestId!==this.weatherRequestId)return;data.source_url=url;this.weather=data;localStorage.setItem('yidan-last-city',JSON.stringify(city));if(this.planningRequested)this.loadAttractions(city,data);this.notify(this.lang==='zh'?`已选择 ${city.name}，继续设置旅行参数`:`${city.name} selected. Now set your trip details.`)}catch(e){if(requestId===this.weatherRequestId){this.weather=null;this.weatherError=this.t('loadFailed');this.notify(this.weatherError)}}finally{clearTimeout(timer);if(requestId===this.weatherRequestId){this.loading=false;this.refreshIcons();if(shouldScroll)nextTick(()=>document.querySelector('#discover')?.scrollIntoView({behavior:'smooth'}))}}},
    async quickSearch(city,shouldScroll=false,requestPlan=false){this.planningRequested=requestPlan;if(city&&typeof city==='object'&&Number.isFinite(city.latitude))return this.selectCity(city,shouldScroll);const rawName=String(city),name=this.resolveGlobalCityQuery(rawName)||rawName,knownRegion=this.resolveKnownRegion(name);if(knownRegion)return this.selectCity({...knownRegion},shouldScroll);this.query=name;this.loading=true;this.weatherError='';try{const res=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(name)}&count=1&language=${this.lang}&format=json`,{cache:'no-store'});const data=await res.json();if(data.results?.[0])await this.selectCity(data.results[0],shouldScroll);else throw new Error()}catch(e){this.weather=null;this.weatherError=this.t('loadFailed');this.notify(this.weatherError)}finally{this.loading=false}},
    async toggleSave(){
      if(!this.selectedCity)return;if(!this.user){this.setAuthMode('login');this.showLogin=true;return}if(this.cloudLoading)return;
      const key=this.cityKey(this.selectedCity),existing=this.savedCities.find(city=>this.cityKey(city)===key);this.cloudLoading=true;this.cloudError='';
      try{
        if(existing){const {error}=await this.supabaseClient.from('saved_cities').delete().eq('user_id',this.user.id).eq('city_key',key);if(error)throw error;this.savedCities=this.savedCities.filter(city=>this.cityKey(city)!==key);this.notify(this.lang==='zh'?'已从云端收藏移除':'Removed from cloud saves')}
        else{const cityData={...this.selectedCity};delete cityData._cloudId;delete cityData._cityKey;const {data,error}=await this.supabaseClient.from('saved_cities').upsert({user_id:this.user.id,city_key:key,city_data:cityData},{onConflict:'user_id,city_key'}).select('id,city_key,city_data,created_at').single();if(error)throw error;this.savedCities=[{...data.city_data,_cloudId:data.id,_cityKey:data.city_key,_savedAt:data.created_at},...this.savedCities];this.notify(this.lang==='zh'?'已同步到云端收藏':'Saved to the cloud')}
      }catch(error){this.cloudError=this.cloudErrorText(error);this.notify(this.cloudError)}finally{this.cloudLoading=false}
    },
    openMyTrips(tab='cities'){if(!this.user){this.setAuthMode('login');this.showLogin=true;return}this.myTripTab=tab;this.showMyTrips=true;this.showProfile=false;this.loadCloudData()},
    async saveCurrentTrip(){
      if(!this.user){this.setAuthMode('login');this.showLogin=true;return}if(!this.selectedCity||!this.itinerary.length)return;
      this.savingTrip=true;this.cloudError='';
      try{const payload={user_id:this.user.id,title:this.currentTripTitle,city_data:{...this.selectedCity},travel_date:this.travelDate,days:this.tripDays,budget:Number(this.budget),itinerary:this.itinerary};const {data,error}=await this.supabaseClient.from('saved_trips').insert(payload).select('id,title,city_data,travel_date,days,budget,itinerary,created_at,updated_at').single();if(error)throw error;this.savedTrips=[data,...this.savedTrips];this.notify(this.lang==='zh'?'行程已保存到“我的旅行”':'Trip saved to My Trips')}
      catch(error){this.cloudError=this.cloudErrorText(error);this.notify(this.cloudError)}finally{this.savingTrip=false}
    },
    async deleteSavedTrip(id){const {error}=await this.supabaseClient.from('saved_trips').delete().eq('id',id).eq('user_id',this.user.id);if(error){this.cloudError=this.cloudErrorText(error);return}this.savedTrips=this.savedTrips.filter(trip=>trip.id!==id)},
    async openSavedCity(city){const {_cloudId,_cityKey,_savedAt,...cityData}=city;this.showMyTrips=false;this.planningRequested=false;await this.selectCity(cityData,false);window.scrollTo({top:0,behavior:'smooth'})},
    async openSavedTrip(trip){this.travelDate=trip.travel_date;this.tripDays=trip.days;this.budget=trip.budget;this.pendingTripItinerary=Array.isArray(trip.itinerary)?trip.itinerary:null;this.showMyTrips=false;this.planningRequested=true;await this.selectCity({...trip.city_data},true)},
    shareCurrentTrip(){if(!this.selectedCity)return;const params=new URLSearchParams({city:this.selectedCity.name,date:this.travelDate,days:String(this.tripDays),budget:String(this.budget)}),url=`${this.authRedirectUrl()}?${params}`;navigator.clipboard?.writeText(url).then(()=>this.notify(this.lang==='zh'?'旅行计划链接已复制':'Trip link copied')).catch(()=>prompt(this.lang==='zh'?'复制这个链接':'Copy this link',url))},
    setPlannerView(view){this.plannerView=view},
    scheduleRouteMap(){clearTimeout(this.mapRenderTimer);if(this.plannerView!=='map')return;this.mapRenderTimer=setTimeout(()=>this.renderRouteMap(),80)},
    escapeHtml(value){return String(value||'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))},
    async renderRouteMap(){
      if(this.plannerView!=='map'||!window.L||!this.activeDayRoutePoints.length)return;await nextTick();const element=document.getElementById('route-map');if(!element)return;
      this.routeMap?.remove();const map=markRaw(window.L.map(element,{zoomControl:true,scrollWheelZoom:false}));this.routeMap=map;
      window.L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);
      const coordinates=[];this.activeDayRoutePoints.forEach((point,index)=>{const lat=Number(point.lat),lon=Number(point.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return;coordinates.push([lat,lon]);const icon=window.L.divIcon({className:'route-number-wrapper',html:`<span class="route-number">${index+1}</span>`,iconSize:[32,32],iconAnchor:[16,16]});window.L.marker([lat,lon],{icon}).addTo(map).bindPopup(`<b>${index+1}. ${this.escapeHtml(point.name)}</b><small>${this.escapeHtml(point.time||'')}</small>`)});
      if(coordinates.length>1)window.L.polyline(coordinates,{color:'#d89a51',weight:5,opacity:.9,dashArray:'10 8',lineCap:'round'}).addTo(map);map.fitBounds(coordinates,{padding:[42,42],maxZoom:15});setTimeout(()=>map.invalidateSize(),120)
    },
    authRedirectUrl(){return location.protocol==='file:'?'https://yidandadi.github.io/yidandadi-travel/':`${location.origin}${location.pathname}`},
    authUser(raw){if(!raw)return null;return{id:raw.id,email:raw.email||'',name:raw.user_metadata?.display_name||raw.user_metadata?.name||(raw.email||'Traveler').split('@')[0],emailConfirmed:Boolean(raw.email_confirmed_at)}},
    async initAuth(){
      localStorage.removeItem('yidan-user');
      const config=window.YIDAN_SUPABASE;
      if(!window.supabase?.createClient||!config?.url||!config?.publishableKey){this.authReady=true;this.authError=this.lang==='zh'?'认证服务配置缺失':'Authentication service is not configured';return}
      this.supabaseClient=window.supabase.createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true},global:{headers:{'x-application-name':'yidan-travel'}}});
      const {data}=this.supabaseClient.auth.onAuthStateChange((event,session)=>{setTimeout(()=>this.handleAuthEvent(event,session),0)});
      this.authSubscription=data.subscription;
      const {data:userData,error}=await this.supabaseClient.auth.getUser();
      if(!error)this.user=this.authUser(userData.user);
      if(this.user)await this.loadCloudData();
      this.authReady=true;
    },
    handleAuthEvent(event,session){
      this.user=this.authUser(session?.user||null);
      if(event==='PASSWORD_RECOVERY'){this.setAuthMode('update');this.showLogin=true;this.authMessage=this.lang==='zh'?'身份验证成功，请设置新密码':'Verified. Set a new password.'}
      if(event==='SIGNED_OUT'){this.showProfile=false;this.savedCities=[];this.savedTrips=[];this.showMyTrips=false}
      else if(session?.user&&['INITIAL_SESSION','SIGNED_IN','USER_UPDATED','TOKEN_REFRESHED'].includes(event))this.loadCloudData()
    },
    cityKey(city){if(!city)return'';return String(city.id||`${city.country_code||city.country||''}:${Number(city.latitude).toFixed(4)}:${Number(city.longitude).toFixed(4)}:${city.name}`)},
    cloudErrorText(error){const missing=['42P01','PGRST205'].includes(error?.code)||/saved_cities|saved_trips|profiles/i.test(error?.message||'');if(missing)return this.lang==='zh'?'云端数据表尚未初始化，请先运行 supabase/migrations 中的 SQL':'Cloud tables are not initialized. Run the SQL migration first.';return this.lang==='zh'?'云同步暂时失败，请稍后重试':'Cloud sync failed. Please try again.'},
    async loadCloudData(){
      if(!this.user||!this.supabaseClient)return;
      this.cloudLoading=true;this.cloudError='';
      try{
        const [profileResult,citiesResult,tripsResult]=await Promise.all([
          this.supabaseClient.from('profiles').select('display_name,avatar_url').eq('id',this.user.id).maybeSingle(),
          this.supabaseClient.from('saved_cities').select('id,city_key,city_data,created_at').order('created_at',{ascending:false}),
          this.supabaseClient.from('saved_trips').select('id,title,city_data,travel_date,days,budget,itinerary,created_at,updated_at').order('updated_at',{ascending:false})
        ]);
        const error=profileResult.error||citiesResult.error||tripsResult.error;if(error)throw error;
        if(profileResult.data?.display_name)this.user={...this.user,name:profileResult.data.display_name,avatarUrl:profileResult.data.avatar_url||''};
        this.savedCities=(citiesResult.data||[]).map(row=>({...row.city_data,_cloudId:row.id,_cityKey:row.city_key,_savedAt:row.created_at}));
        this.savedTrips=tripsResult.data||[];
      }catch(error){this.cloudError=this.cloudErrorText(error)}finally{this.cloudLoading=false}
    },
    setAuthMode(mode){this.authMode=mode;this.authError='';this.authMessage='';this.showPassword=false;this.showConfirmPassword=false;this.loginForm.password='';this.loginForm.confirmPassword=''},
    authErrorText(error){const message=String(error?.message||'');if(this.lang==='en')return message||'Authentication failed. Please try again.';if(/Invalid login credentials/i.test(message))return'邮箱或密码不正确';if(/Email not confirmed/i.test(message))return'请先打开验证邮件完成邮箱确认';if(/User already registered/i.test(message))return'该邮箱已经注册，请直接登录';if(/Password should be at least/i.test(message))return'密码至少需要 8 位';if(/rate limit/i.test(message))return'操作过于频繁，请稍后再试';if(/Unable to validate email/i.test(message))return'邮箱格式不正确';return message||'认证失败，请稍后重试'},
    async submitAuth(){
      if(!this.supabaseClient){this.authError=this.lang==='zh'?'认证服务暂时不可用':'Authentication is unavailable';return}
      const email=this.loginForm.email.trim(),password=this.loginForm.password,name=this.loginForm.name.trim();
      this.authError='';this.authMessage='';
      if(this.authMode!=='update'&&!/^\S+@\S+\.\S+$/.test(email)){this.authError=this.lang==='zh'?'请输入有效邮箱':'Enter a valid email';return}
      if(['login','register','update'].includes(this.authMode)&&password.length<8){this.authError=this.lang==='zh'?'密码至少需要 8 位':'Password must be at least 8 characters';return}
      if(['register','update'].includes(this.authMode)&&password!==this.loginForm.confirmPassword){this.authError=this.lang==='zh'?'两次输入的密码不一致':'Passwords do not match';return}
      if(this.authMode==='register'&&!name){this.authError=this.lang==='zh'?'请输入昵称':'Enter a display name';return}
      this.authLoading=true;
      try{
        if(this.authMode==='register'){
          const {data,error}=await this.supabaseClient.auth.signUp({email,password,options:{data:{display_name:name},emailRedirectTo:this.authRedirectUrl()}});if(error)throw error;
          if(data.session){this.user=this.authUser(data.user);this.showLogin=false;this.notify(this.lang==='zh'?`欢迎，${this.user.name}！`:`Welcome, ${this.user.name}!`)}else{this.authMode='verify';this.authMessage=this.lang==='zh'?`验证邮件已发送到 ${email}`:`Verification email sent to ${email}`}
        }else if(this.authMode==='login'){
          const {data,error}=await this.supabaseClient.auth.signInWithPassword({email,password});if(error)throw error;this.user=this.authUser(data.user);this.showLogin=false;this.loginForm.password='';this.notify(this.lang==='zh'?`欢迎回来，${this.user.name}！`:`Welcome back, ${this.user.name}!`)
        }else if(this.authMode==='forgot'){
          const {error}=await this.supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:this.authRedirectUrl()});if(error)throw error;this.authMode='verify';this.authMessage=this.lang==='zh'?`密码重置邮件已发送到 ${email}`:`Password reset email sent to ${email}`
        }else if(this.authMode==='update'){
          const {data,error}=await this.supabaseClient.auth.updateUser({password});if(error)throw error;this.user=this.authUser(data.user);this.showLogin=false;this.loginForm.password='';this.loginForm.confirmPassword='';this.notify(this.lang==='zh'?'密码已更新，请妥善保管':'Password updated successfully')
        }
      }catch(error){this.authError=this.authErrorText(error)}finally{this.authLoading=false}
    },
    async logout(){if(!this.supabaseClient)return;this.authLoading=true;const {error}=await this.supabaseClient.auth.signOut();this.authLoading=false;if(error){this.notify(this.authErrorText(error));return}this.user=null;this.showProfile=false;this.notify(this.lang==='zh'?'已安全退出登录':'Signed out securely')},
    chooseSuggestion(city){this.planningRequested=false;return this.selectCity(city,false)},
    toggleInterest(id){this.travelInterests=this.travelInterests.includes(id)?this.travelInterests.filter(item=>item!==id):[...this.travelInterests,id]},
    interestScore(place){const kind=place.kind||'',selected=new Set(this.travelInterests);let score=0;if(selected.has('nature')&&['park','viewpoint'].includes(kind))score+=12;if(selected.has('culture')&&['museum','gallery','memorial','monument','castle','temple','archaeological_site'].includes(kind))score+=12;if(selected.has('photo')&&['viewpoint','attraction','monument','castle','temple'].includes(kind))score+=10;if(selected.has('fun')&&['theme_park','aquarium','zoo','attraction'].includes(kind))score+=10;if(selected.has('slow')&&['park','museum','gallery'].includes(kind))score+=8;return score},
    async startPlanning(){if(!this.selectedCity||!this.weather)return;this.onPreferencesChange();this.planningRequested=true;const supportPromise=this.loadSupportPlaces(this.selectedCity);await this.loadAttractions(this.selectedCity,this.weather);await supportPromise;if(!this.itinerary.length&&this.attractions.length&&this.restaurants.length&&this.hotels.length)this.generateItinerary(this.weather);nextTick(()=>document.querySelector('#planner')?.scrollIntoView({behavior:'smooth'}))},
    mobileNavigate(target){this.showMobileMenu=false;nextTick(()=>document.querySelector(target)?.scrollIntoView({behavior:'smooth'}))},
    onPreferencesChange(){this.tripDays=Math.max(1,Math.min(7,Number(this.tripDays)||3));this.budget=Math.max(500,Math.min(30000,Number(this.budget)||3800));if(this.travelDate>this.maxTravelDate)this.travelDate=this.maxTravelDate;localStorage.setItem('yidan-budget',this.budget);localStorage.setItem('yidan-trip-days',this.tripDays);if(this.planningRequested&&this.weather&&this.attractions.length)this.generateItinerary()},
    estimateAttractionCost(kind){const costs={park:0,viewpoint:20,memorial:20,monument:20,temple:30,castle:60,attraction:50,museum:80,gallery:70,zoo:140,aquarium:180,theme_park:320};return costs[kind]??40},
    async fetchOverpass(query,endpoints){const attempts=endpoints.map(async endpoint=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const res=await fetch(endpoint+'?data='+encodeURIComponent(query),{cache:'no-store',signal:controller.signal});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();if(!data.elements?.length)throw new Error('Empty Overpass result');return data}finally{clearTimeout(timer)}});try{return await Promise.any(attempts)}catch{return null}},
    async loadSupportPlaces(city){if(this.supportPlacesPromise)return this.supportPlacesPromise;this.supportPlacesPromise=this.fetchSupportPlaces(city);try{return await this.supportPlacesPromise}finally{this.supportPlacesPromise=null}},
    async fetchSupportPlaces(city){this.supportPlacesLoading=true;const cacheKey=`yidan-support-${city.id}-${this.lang}`;try{const cached=JSON.parse(localStorage.getItem(cacheKey)||'null');if(cached&&Date.now()-cached.savedAt<21600000&&cached.restaurants?.length>=4&&cached.hotels?.length){this.restaurants=cached.restaurants;this.hotels=cached.hotels;this.supportPlacesLoading=false;return true}}catch(e){}const lat=Number(city.latitude),lon=Number(city.longitude),south=(lat-.015).toFixed(5),north=(lat+.015).toFixed(5),west=(lon-.020).toFixed(5),east=(lon+.020).toFixed(5),box=`${south},${west},${north},${east}`,query=`[out:json][timeout:12];(node["amenity"~"restaurant|food_court|fast_food"]["name"](${box});node["tourism"~"hotel|hostel|guest_house"]["name"](${box}););out body 70;`,endpoints=['https://maps.mail.ru/osm/tools/overpass/api/interpreter','https://overpass.private.coffee/api/interpreter'];try{const data=await this.fetchOverpass(query,endpoints);if(!data||this.selectedCity?.id!==city.id)return false;const seen=new Set(),items=(data.elements||[]).map(e=>{const t=e.tags||{},name=t[`name:${this.lang}`]||t['name:zh']||t.name||t['name:en'],point=e.center||e;if(!name||!Number.isFinite(point.lat)||!Number.isFinite(point.lon))return null;const key=name.toLocaleLowerCase();if(seen.has(key))return null;seen.add(key);return{name,lat:point.lat,lon:point.lon,amenity:t.amenity||'',tourism:t.tourism||'',cuisine:t.cuisine||'',mapUrl:`https://www.openstreetmap.org/?mlat=${point.lat}&mlon=${point.lon}#map=17/${point.lat}/${point.lon}`}}).filter(Boolean);this.restaurants=items.filter(p=>['restaurant','food_court','fast_food'].includes(p.amenity));this.hotels=items.filter(p=>['hotel','hostel','guest_house'].includes(p.tourism));if(this.restaurants.length<4||!this.hotels.length)throw new Error('Not enough route support places');localStorage.setItem(cacheKey,JSON.stringify({savedAt:Date.now(),restaurants:this.restaurants,hotels:this.hotels}));return true}catch(e){this.planError=this.t('planFailed');return false}finally{this.supportPlacesLoading=false}},
    distanceKm(a,b){if(!a||!b)return 999;const rad=Math.PI/180,dLat=(b.lat-a.lat)*rad,dLon=(b.lon-a.lon)*rad,x=Math.sin(dLat/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))},
    nearestUnused(list,anchor,used){return [...list].filter(p=>!used.has(p.name)).sort((a,b)=>this.distanceKm(a,anchor)-this.distanceKm(b,anchor))[0]||null},
    foodDescription(place,language=this.lang){const raw=(place.cuisine||'').split(';')[0].replaceAll('_',' ');if(raw)return language==='zh'?`${raw} 风味 · 靠近上一站`:`${raw} cuisine · near the previous stop`;return language==='zh'?(place.amenity==='fast_food'?'平价快捷餐饮 · 靠近上一站':'当地餐厅 · 靠近上一站'):(place.amenity==='fast_food'?'Affordable quick meal · near the route':'Local restaurant · near the route')},
    stayEstimate(place){const d=this.dailyBudget;if(d<500)return place.tourism==='hostel'?100:160;if(d<1500)return place.tourism==='hostel'?180:place.tourism==='guest_house'?240:360;return place.tourism==='hotel'?650:420},
    async loadAttractions(city,weather=this.weather){this.attractionsLoading=true;this.planError='';this.itinerary=[];const cacheKey=`yidan-attractions-${city.id}-${this.lang}`;try{const cached=JSON.parse(localStorage.getItem(cacheKey)||'null');if(cached&&Date.now()-cached.savedAt<21600000&&cached.items?.length>=3){this.attractions=cached.items;this.generateItinerary(weather);this.attractionsLoading=false;return}}catch(e){}const lat=Number(city.latitude),lon=Number(city.longitude),south=(lat-.045).toFixed(5),north=(lat+.045).toFixed(5),west=(lon-.055).toFixed(5),east=(lon+.055).toFixed(5),box=`${south},${west},${north},${east}`;const query=`[out:json][timeout:12];(nwr["tourism"~"attraction|museum|gallery|viewpoint|aquarium|theme_park"]["name"](${box});nwr["historic"~"monument|memorial|castle|temple|archaeological_site"]["name"](${box});nwr["leisure"="park"]["name"](${box}););out tags center 60;`,endpoints=['https://maps.mail.ru/osm/tools/overpass/api/interpreter','https://overpass.private.coffee/api/interpreter'];try{const data=await this.fetchOverpass(query,endpoints);if(!data)throw new Error('All Overpass endpoints failed');if(this.selectedCity?.id!==city.id)return;const seen=new Set(),ranked=(data.elements||[]).map(e=>{const t=e.tags||{},name=t[`name:${this.lang}`]||t['name:zh']||t.name||t['name:en'];if(!name)return null;const key=name.toLocaleLowerCase();if(seen.has(key))return null;seen.add(key);const kind=t.tourism||t.historic||t.leisure||'attraction';const indoor=['museum','gallery','aquarium'].includes(kind),point=e.center||e;let score=(t.wikipedia?8:0)+(t.wikidata?5:0)+(t.website?1:0)+(t['name:zh']||t['name:en']?2:0)+(['attraction','viewpoint','castle','temple'].includes(kind)?4:0)+(['museum','gallery','aquarium'].includes(kind)?3:1);return{name,kind,indoor,lat:point.lat,lon:point.lon,score,mapUrl:`https://www.openstreetmap.org/?mlat=${point.lat}&mlon=${point.lon}#map=16/${point.lat}/${point.lon}`}}).filter(p=>p&&Number.isFinite(p.lat)&&Number.isFinite(p.lon)).sort((a,b)=>b.score-a.score);this.attractions=[...ranked.filter(p=>!p.indoor).slice(0,12),...ranked.filter(p=>p.indoor).slice(0,12)];if(this.attractions.length<3)throw new Error('Not enough named attractions');localStorage.setItem(cacheKey,JSON.stringify({savedAt:Date.now(),items:this.attractions}));this.generateItinerary(weather)}catch(e){this.planError=this.t('planFailed');this.itinerary=[]}finally{this.attractionsLoading=false}},
    attractionLabel(kind,language=this.lang){const zh={museum:'博物馆',gallery:'美术馆',viewpoint:'观景台',zoo:'动物园',aquarium:'水族馆',theme_park:'主题乐园',park:'城市公园',memorial:'历史纪念地',monument:'历史地标',castle:'城堡',temple:'寺庙',shrine:'神社',attraction:'人气景点'};const en={museum:'Museum',gallery:'Gallery',viewpoint:'Viewpoint',zoo:'Zoo',aquarium:'Aquarium',theme_park:'Theme park',park:'Park',memorial:'Memorial',monument:'Historic landmark',castle:'Castle',temple:'Temple',shrine:'Shrine',attraction:'Attraction'};return(language==='zh'?zh:en)[kind]||(language==='zh'?'当地景点':'Local attraction')},
    generateItinerary(weather=this.weather){
      if(!weather||!this.attractions.length)return;
      if(!this.restaurants.length||!this.hotels.length){
        this.loadSupportPlaces(this.selectedCity).then(ok=>{if(ok)this.generateItinerary(weather)});
        return;
      }
      const start=this.travelWeatherIndex,lowBudget=this.dailyBudget<500,midBudget=this.dailyBudget<1500;
      const enriched=this.attractions.map(p=>({...p,score:(p.score||0)+this.interestScore(p),estimatedCost:this.estimateAttractionCost(p.kind)}));
      const rank=list=>[...list].sort((a,b)=>lowBudget?(a.estimatedCost-b.estimatedCost)||(b.score-a.score):(b.score-a.score)||(a.estimatedCost-b.estimatedCost));
      const indoor=rank(enriched.filter(p=>p.indoor)),outdoor=rank(enriched.filter(p=>!p.indoor)),all=rank(enriched);
      const usedAttractions=new Set(),usedRestaurants=new Set(),plan=[];
      const center={lat:Number(this.selectedCity.latitude),lon:Number(this.selectedCity.longitude)};
      const hotelTier=p=>lowBudget?({hostel:0,guest_house:1,hotel:2}[p.tourism]??3):midBudget?({guest_house:0,hotel:1,hostel:2}[p.tourism]??3):({hotel:0,guest_house:1,hostel:2}[p.tourism]??3);
      const hotel=[...this.hotels].sort((a,b)=>(hotelTier(a)-hotelTier(b))||this.distanceKm(a,center)-this.distanceKm(b,center))[0];
      const ticketLimit=Math.round(this.dailyBudget*(lowBudget?.2:midBudget?.3:.36));
      const routeUrl=(a,b)=>`https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=${a.lat}%2C${a.lon}%3B${b.lat}%2C${b.lon}`;
      const chooseSeed=(preferred,dayUsed)=>{
        let candidates=[...preferred,...all].filter((p,i,a)=>!usedAttractions.has(p.name)&&!dayUsed.has(p.name)&&a.findIndex(x=>x.name===p.name)===i);
        if(!candidates.length)candidates=all.filter(p=>!dayUsed.has(p.name));
        return candidates.find(p=>p.estimatedCost<=ticketLimit)||candidates[0]||null;
      };
      const chooseNear=(anchor,preferred,dayUsed)=>{
        let candidates=[...preferred,...all].filter((p,i,a)=>!usedAttractions.has(p.name)&&!dayUsed.has(p.name)&&a.findIndex(x=>x.name===p.name)===i);
        if(!candidates.length)candidates=all.filter(p=>!dayUsed.has(p.name));
        return candidates.sort((a,b)=>this.distanceKm(a,anchor)-this.distanceKm(b,anchor))[0]||null;
      };
      const chooseMeal=(anchor,meal,dayUsed)=>{
        const foodFocused=this.travelInterests.includes('food'),preferred=this.restaurants.filter(p=>lowBudget?(p.amenity!=='restaurant'||meal==='dinner'):p.amenity==='restaurant');
        let candidates=[...preferred,...this.restaurants].filter((p,i,a)=>!usedRestaurants.has(p.name)&&!dayUsed.has(p.name)&&a.findIndex(x=>x.name===p.name)===i);
        if(!candidates.length)candidates=this.restaurants.filter(p=>!dayUsed.has(p.name));
        return candidates.sort((a,b)=>(foodFocused?(Number(Boolean(b.cuisine))-Number(Boolean(a.cuisine))):0)||(this.distanceKm(a,anchor)-this.distanceKm(b,anchor)))[0]||null;
      };
      for(let day=0;day<this.tripDays;day++){
        const weatherDay=Math.min(start+day,weather.daily.time.length-1),rain=weather.daily.precipitation_probability_max[weatherDay]||0,max=Math.round(weather.daily.temperature_2m_max[weatherDay]),code=weather.daily.weather_code[weatherDay],rainy=rain>=50;
        const preferred=rainy?indoor:outdoor,dayAttractions=new Set(),dayMeals=new Set();
        const morningA=chooseSeed(preferred,dayAttractions);if(!morningA)continue;dayAttractions.add(morningA.name);usedAttractions.add(morningA.name);
        const morningB=chooseNear(morningA,preferred,dayAttractions)||morningA;dayAttractions.add(morningB.name);usedAttractions.add(morningB.name);
        const lunch=chooseMeal(morningB,'lunch',dayMeals);if(lunch){dayMeals.add(lunch.name);usedRestaurants.add(lunch.name)}
        const afternoonA=chooseNear(lunch||morningB,rainy?indoor:outdoor,dayAttractions)||morningB;dayAttractions.add(afternoonA.name);usedAttractions.add(afternoonA.name);
        const afternoonB=chooseNear(afternoonA,rainy?indoor:outdoor,dayAttractions)||afternoonA;dayAttractions.add(afternoonB.name);usedAttractions.add(afternoonB.name);
        const dinner=chooseMeal(afternoonB,'dinner',dayMeals)||lunch;if(dinner){dayMeals.add(dinner.name);usedRestaurants.add(dinner.name)}
        const dateLabel=this.formatShortDate(weather.daily.time[weatherDay]),forecast=`${this.weatherIcon(code)} ${max}° · ☂ ${rain}%`;
        const weatherZh=rainy?`降水概率 ${rain}%，以室内景点为主并预留避雨时间`:(max>=30?'避开正午高温，户外景点集中在早晚':`天气适合步行串联，最高 ${max}°`);
        const weatherEn=rainy?`${rain}% rain chance; indoor stops lead the route`:(max>=30?'Outdoor stops avoid the hottest midday period':`Comfortable for a connected walking route, high ${max}°`);
        const morningDistance=this.distanceKm(morningA,morningB).toFixed(1),afternoonDistance=this.distanceKm(afternoonA,afternoonB).toFixed(1);
        plan.push({day:day+1,type:'morningRoute',dateLabel,time:'09:00–11:45',icon:'sunrise',zh:`${morningA.name} → ${morningB.name}`,en:`${morningA.name} → ${morningB.name}`,descZh:`先游览${this.attractionLabel(morningA.kind,'zh')}，再步行/短途前往${this.attractionLabel(morningB.kind,'zh')} · 两站约 ${morningDistance} km · ${weatherZh}`,descEn:`Start at a ${this.attractionLabel(morningA.kind,'en')}, then continue to a nearby ${this.attractionLabel(morningB.kind,'en')} · ${morningDistance} km between stops · ${weatherEn}`,forecast,estimatedCost:morningA.estimatedCost+morningB.estimatedCost,mapUrl:routeUrl(morningA,morningB),points:[{name:morningA.name,lat:morningA.lat,lon:morningA.lon},{name:morningB.name,lat:morningB.lat,lon:morningB.lon}]});
        if(lunch){const lunchCost=lowBudget?35:midBudget?70:140,dist=this.distanceKm(morningB,lunch).toFixed(1);plan.push({day:day+1,type:'lunch',dateLabel,time:'12:00–13:15',icon:'utensils',zh:lunch.name,en:lunch.name,descZh:`${this.foodDescription(lunch,'zh')} · 距上午终点约 ${dist} km，午餐后少走回头路`,descEn:`${this.foodDescription(lunch,'en')} · about ${dist} km from the last stop`,forecast,estimatedCost:lunchCost,mapUrl:lunch.mapUrl,points:[{name:lunch.name,lat:lunch.lat,lon:lunch.lon}]})}
        plan.push({day:day+1,type:'afternoonRoute',dateLabel,time:'13:45–17:30',icon:rainy?'landmark':'camera',zh:`${afternoonA.name} → ${afternoonB.name}`,en:`${afternoonA.name} → ${afternoonB.name}`,descZh:`午餐后就近出发，连续游览两处景点 · 两站约 ${afternoonDistance} km · ${weatherZh}`,descEn:`Continue from lunch through two nearby sights · ${afternoonDistance} km between stops · ${weatherEn}`,forecast,estimatedCost:afternoonA.estimatedCost+afternoonB.estimatedCost,mapUrl:routeUrl(afternoonA,afternoonB),points:[{name:afternoonA.name,lat:afternoonA.lat,lon:afternoonA.lon},{name:afternoonB.name,lat:afternoonB.lat,lon:afternoonB.lon}]});
        if(dinner){const dinnerCost=lowBudget?50:midBudget?110:240,dist=this.distanceKm(afternoonB,dinner).toFixed(1);plan.push({day:day+1,type:'dinner',dateLabel,time:'18:00–19:30',icon:'soup',zh:dinner.name,en:dinner.name,descZh:`${this.foodDescription(dinner,'zh')} · 距下午终点约 ${dist} km，适合作为当日收尾`,descEn:`${this.foodDescription(dinner,'en')} · about ${dist} km from the final attraction`,forecast,estimatedCost:dinnerCost,mapUrl:dinner.mapUrl,points:[{name:dinner.name,lat:dinner.lat,lon:dinner.lon}]})}
        if(hotel){const dist=this.distanceKm(dinner||afternoonB,hotel).toFixed(1),tierZh=lowBudget?'经济型住宿（优先性价比）':midBudget?'舒适住宿':'品质酒店',tierEn=lowBudget?'budget stay':midBudget?'comfortable stay':'quality hotel';plan.push({day:day+1,type:'stay',dateLabel,time:'20:00 后',icon:'bed-double',zh:hotel.name,en:hotel.name,descZh:`${tierZh} · 距晚餐约 ${dist} km · 连续入住同一家，减少每天搬运行李`,descEn:`Recommended ${tierEn} · about ${dist} km from dinner · stay here throughout to avoid moving luggage`,forecast,estimatedCost:this.stayEstimate(hotel),mapUrl:hotel.mapUrl,points:[{name:hotel.name,lat:hotel.lat,lon:hotel.lon}]})}
      }
      this.itinerary=this.pendingTripItinerary?.length?this.pendingTripItinerary:plan;this.pendingTripItinerary=null;this.activeDay=1;this.refreshIcons();this.scheduleRouteMap();
      this.notify(this.lang==='zh'?`已生成 ${this.tripDays} 天旅行社式完整路线`:`Generated a complete ${this.tripDays}-day agency-style route`)
    },
    addActivity(){this.generateItinerary()},removeActivity(i){this.itinerary.splice(i,1)},
    weatherIcon(c){if(c===0)return'☀️';if(c<=3)return'⛅';if(c<=48)return'🌫️';if(c<=67)return'🌧️';if(c<=77)return'🌨️';if(c<=82)return'🌦️';return'⛈️'},weatherText(c){const zh=c===0?'晴朗':c<=3?'多云':c<=48?'有雾':c<=67?'有雨':c<=77?'有雪':c<=82?'阵雨':'雷雨';const en=c===0?'Clear':c<=3?'Cloudy':c<=48?'Foggy':c<=67?'Rainy':c<=77?'Snowy':c<=82?'Showers':'Stormy';return this.lang==='zh'?zh:en},
    formatShortDate(d){return new Intl.DateTimeFormat(this.lang==='zh'?'zh-CN':'en-US',{month:'numeric',day:'numeric'}).format(new Date(d))},dayDateLabel(day){return this.itinerary.find(item=>item.day===day)?.dateLabel||''},formatDate(d){return new Intl.DateTimeFormat(this.lang==='zh'?'zh-CN':'en-US',{month:'long',day:'numeric',weekday:'long'}).format(new Date(d))},formatTime(d){return new Intl.DateTimeFormat(this.lang==='zh'?'zh-CN':'en-US',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:this.weather?.timezone||undefined}).format(new Date(d))},dayName(d){return new Intl.DateTimeFormat(this.lang==='zh'?'zh-CN':'en-US',{weekday:'short'}).format(new Date(d))},notify(msg){this.toast=msg;this.refreshIcons();setTimeout(()=>this.toast='',2600)}
  }
}).mount('#app');
