const { createApp, nextTick } = Vue;

const chinaRegionRows = [
  ['北京市','北京',39.9042,116.4074],['天津市','天津',39.0851,117.1994],['河北省','石家庄',38.0428,114.5149],['山西省','太原',37.8706,112.5489],
  ['内蒙古自治区','呼和浩特',40.8426,111.7492],['辽宁省','沈阳',41.8057,123.4315],['吉林省','长春',43.8171,125.3235],['黑龙江省','哈尔滨',45.8038,126.5349],
  ['上海市','上海',31.2304,121.4737],['江苏省','南京',32.0603,118.7969],['浙江省','杭州',30.2741,120.1551],['安徽省','合肥',31.8206,117.2272],
  ['福建省','福州',26.0745,119.2965],['江西省','南昌',28.682,115.8579],['山东省','济南',36.6512,117.1201],['河南省','郑州',34.7466,113.6254],
  ['湖北省','武汉',30.5928,114.3055],['湖南省','长沙',28.2282,112.9388],['广东省','广州',23.1291,113.2644],['广西壮族自治区','南宁',22.817,108.3665],
  ['海南省','海口',20.044,110.1999],['重庆市','重庆',29.563,106.5516],['四川省','成都',30.5728,104.0668],['贵州省','贵阳',26.647,106.6302],
  ['云南省','昆明',25.0389,102.7183],['西藏自治区','拉萨',29.6525,91.1721],['陕西省','西安',34.3416,108.9398],['甘肃省','兰州',36.0611,103.8343],
  ['青海省','西宁',36.6171,101.7782],['宁夏回族自治区','银川',38.4872,106.2309],['新疆维吾尔自治区','乌鲁木齐',43.8256,87.6168],
  ['香港特别行政区','香港',22.3193,114.1694],['澳门特别行政区','澳门',22.1987,113.5439],['台湾省','台北',25.033,121.5654]
];
const chinaRegionLookup = new Map();
chinaRegionRows.forEach((row,index)=>{
  const [name,capital,latitude,longitude]=row;
  const item={id:`CN-ADM1-${index}`,name,admin1:name,admin2:capital,country:'中国',country_code:'CN',latitude,longitude,feature_code:'ADM1',regionLabel:`行政中心 ${capital} 代表点`};
  const short=name.replace(/特别行政区$|维吾尔自治区$|壮族自治区$|回族自治区$|自治区$|省$|市$/,'');
  [name,short,`中国${name}`,`中国${short}`].forEach(alias=>chinaRegionLookup.set(alias,item));
  if(name==='台湾省')['台湾','臺灣','臺灣省','中国台湾','中國臺灣'].forEach(alias=>chinaRegionLookup.set(alias,item));
});

createApp({
  data(){return{
    lang:localStorage.getItem('yidan-lang')||'zh',darkMode:localStorage.getItem('yidan-dark')==='true',scrolled:false,showLogin:false,showProfile:false,loading:false,toast:'',query:'',suggestions:[],selectedCity:null,weather:null,weatherError:'',weatherRequestId:0,travelDate:new Date().toISOString().slice(0,10),today:new Date().toISOString().slice(0,10),user:JSON.parse(localStorage.getItem('yidan-user')||'null'),loginForm:{name:'',email:''},savedCities:JSON.parse(localStorage.getItem('yidan-saved')||'[]'),budget:3800,
    quickCities:[
      {id:1816670,name:'北京',admin1:'北京',country:'中国',latitude:39.9075,longitude:116.39723,label:{zh:'北京',en:'Beijing'}},
      {id:1808926,name:'杭州',admin1:'浙江',country:'中国',latitude:30.29365,longitude:120.16142,label:{zh:'杭州',en:'Hangzhou'}},
      {id:1850147,name:'東京',admin1:'東京都',country:'日本',latitude:35.6895,longitude:139.69171,label:{zh:'东京',en:'Tokyo'}},
      {id:2988507,name:'Paris',admin1:'Île-de-France',country:'France',latitude:48.85341,longitude:2.3488,label:{zh:'巴黎',en:'Paris'}}
    ],
    attractions:[],attractionsLoading:false,planError:'',itinerary:[],
    destinations:[
      {search:'Dali',emoji:'🏔️',gradient:'linear-gradient(145deg,#b7d5cd,#56877c)',tagZh:'山野治愈',tagEn:'Mountain retreat',zh:'云南 · 大理',en:'Dali · Yunnan',descZh:'苍山洱海之间，寻找风、花与慢生活。',descEn:'Find slow living between Cangshan and Erhai.'},
      {search:'Kyoto',emoji:'⛩️',gradient:'linear-gradient(145deg,#e2c7a0,#b6754d)',tagZh:'文化漫游',tagEn:'Culture journey',zh:'日本 · 京都',en:'Kyoto · Japan',descZh:'穿过古寺与町屋，遇见四季流转。',descEn:'Walk through temples and timeless seasons.'},
      {search:'Reykjavik',emoji:'🌌',gradient:'linear-gradient(145deg,#8496ad,#283f51)',tagZh:'极境探索',tagEn:'Wild escape',zh:'冰岛 · 雷克雅未克',en:'Reykjavik · Iceland',descZh:'火山、冰川与极光构成的梦幻旅程。',descEn:'Volcanoes, glaciers and northern lights.'}
    ],
    i18n:{
      zh:{brand:'亿蛋大帝旅游宝',discover:'探索目的地',planner:'行程规划',inspiration:'旅行灵感',theme:'切换主题',login:'登录',logout:'退出登录',eyebrow:'为每一次出发，找到更好的答案',heroTitle1:'世界很大，',heroTitle2:'出发正好。',heroSub:'输入全球任意城市，我们会结合天气预报，为你生成贴心的旅行建议与轻松可行的行程。',where:'目的地',cityPlaceholder:'搜索全球城市，如：东京、伦敦',when:'出发日期',explore:'开始探索',searching:'正在寻找',popular:'热门搜索',scroll:'向下探索',liveWeather:'全球天气预报',ready:'今天适合出发吗？',save:'收藏城市',saved:'已收藏',feels:'体感',high:'最高',low:'最低',humidity:'湿度',wind:'风速',rain:'降水',smartAdvice:'智能出行建议',pack:'建议携带',tripPlanner:'天气智能行程',planTitle:'真实景点，按天气聪明安排。',planSub:'我们从当地真实景点中挑选目的地，晴天优先地标、公园与观景台，雨天优先博物馆、画廊与室内场馆。',feature1:'真实当地景点数据',feature2:'三日天气自适应排序',feature3:'一键打开地图导航',myTrip:'为你生成的三日行程',dreamTrip:'选择城市后生成',activities:'个真实景点',addActivity:'重新按天气生成',estimated:'预计旅行预算',placesTitle:'下一站，去哪里？',placesSub:'为你挑选三种截然不同的旅行心情。',footer:'让每一次出发，都从容而值得。',welcome:'欢迎回来，旅行家',loginSub:'登录后即可收藏目的地与保存偏好。',name:'你的昵称',namePh:'例如：亿蛋大帝',email:'邮箱',startJourney:'开启旅程',privacy:'演示模式：信息仅保存在你的浏览器中',chooseCity:'请选择准确的城市',loadFailed:'天气数据加载失败，请重试',retry:'重新加载',dataTime:'数据时刻',rawData:'查看 API 原始数据',forecastNote:'Open-Meteo Best Match 预报模型（不是气象站实测）',findingPlaces:'正在发现当地真实景点…',planFailed:'当地景点数据暂时加载失败，请重试',openMap:'地图',placeSource:'景点来自 OpenStreetMap，天气来自 Open-Meteo'},
      en:{brand:'Yidan Travel',discover:'Discover',planner:'Trip Planner',inspiration:'Inspiration',theme:'Toggle theme',login:'Sign in',logout:'Sign out',eyebrow:'A better answer for every departure',heroTitle1:'The world is wide.',heroTitle2:'Go now.',heroSub:'Search any city worldwide. We combine global forecasts with thoughtful advice to make every journey easier.',where:'Destination',cityPlaceholder:'Search anywhere, e.g. Tokyo or London',when:'Departure',explore:'Explore',searching:'Searching',popular:'Trending',scroll:'Explore more',liveWeather:'Global weather forecast',ready:'Is today a good day to go?',save:'Save city',saved:'Saved',feels:'Feels',high:'High',low:'Low',humidity:'Humidity',wind:'Wind',rain:'Rain',smartAdvice:'Smart travel advice',pack:'Pack this',tripPlanner:'Weather-smart itinerary',planTitle:'Real places, intelligently scheduled.',planSub:'We select real local attractions, prioritizing landmarks, parks and viewpoints on clear days and museums, galleries and indoor venues when rain is likely.',feature1:'Real local attraction data',feature2:'3-day weather-aware ordering',feature3:'One-click map navigation',myTrip:'Your generated 3-day trip',dreamTrip:'Choose a city to generate',activities:'real places',addActivity:'Regenerate for the weather',estimated:'Estimated trip budget',placesTitle:'Where to next?',placesSub:'Three completely different moods, handpicked for you.',footer:'Make every departure effortless and worthwhile.',welcome:'Welcome back, traveler',loginSub:'Sign in to save destinations and preferences.',name:'Your name',namePh:'e.g. Yidan',email:'Email',startJourney:'Start the journey',privacy:'Demo mode: your data stays in this browser',chooseCity:'Choose the exact city',loadFailed:'Weather data failed to load. Please retry.',retry:'Try again',dataTime:'Data time',rawData:'View raw API data',forecastNote:'Open-Meteo Best Match forecast model (not a station observation)',findingPlaces:'Finding real local attractions…',planFailed:'Local attraction data failed to load. Please retry.',openMap:'Map',placeSource:'Places from OpenStreetMap; weather from Open-Meteo'}
    }
  }},
  computed:{
    isSaved(){return this.selectedCity&&this.savedCities.some(c=>c.id===this.selectedCity.id)},
    smartAdvice(){if(!this.weather)return{title:'',text:'',items:[]};const max=this.weather.daily.temperature_2m_max[0],rain=this.weather.daily.precipitation_probability_max[0],wind=this.weather.current.wind_speed_10m;if(this.lang==='zh'){if(rain>=60)return{title:'把雨也变成旅行的一部分',text:'今天降水概率较高，优先安排博物馆、咖啡馆与室内景点，雨歇时再去城市漫步。',items:['折叠伞','防水鞋','轻薄外套']};if(max>=30)return{title:'避开正午，拥抱清晨与傍晚',text:'天气偏热，建议把户外活动放在早晚，午后留给室内体验，并及时补水。',items:['防晒霜','水杯','遮阳帽']};if(max<=10)return{title:'穿暖一点，慢慢探索',text:'气温较低，分层穿搭会更舒适。选择温暖的餐厅作为途中停靠点。',items:['保暖外套','围巾','润唇膏']};return{title:'很适合步行探索的一天',text:`气温舒适${wind>25?'、风力稍大':'、降水风险较低'}，推荐安排城市漫步、地标打卡和一顿户外晚餐。`,items:['舒适鞋','充电宝','薄外套']}}else{if(rain>=60)return{title:'Make rain part of the journey',text:'Rain is likely. Prioritize museums and cafés, then explore outside between showers.',items:['Umbrella','Waterproof shoes','Light jacket']};if(max>=30)return{title:'Own the morning and evening',text:'It will be hot. Plan outdoor time early or late and stay hydrated.',items:['Sunscreen','Water bottle','Sun hat']};if(max<=10)return{title:'Layer up and take it slow',text:'Cool conditions call for layers and warm café stops along the way.',items:['Warm coat','Scarf','Lip balm']};return{title:'A wonderful day to explore on foot',text:'Comfortable temperatures make today great for city walks, landmarks and dinner outdoors.',items:['Walking shoes','Power bank','Light jacket']}}
    }
  },
  watch:{darkMode(v){localStorage.setItem('yidan-dark',v);this.refreshIcons()},lang(v){localStorage.setItem('yidan-lang',v);document.documentElement.lang=v==='zh'?'zh-CN':'en';this.refreshIcons()},weather(){this.refreshIcons()},showLogin(){this.refreshIcons()},showProfile(){this.refreshIcons()},itinerary:{deep:true,handler(v){if(this.selectedCity)localStorage.setItem(`yidan-itinerary-${this.selectedCity.id}`,JSON.stringify(v))}}},
  mounted(){window.addEventListener('scroll',()=>this.scrolled=window.scrollY>30);this.refreshIcons();const sharedCity=new URLSearchParams(location.search).get('city');setTimeout(()=>this.quickSearch(sharedCity||this.quickCities[1],false),300)},
  methods:{
    t(k){return this.i18n[this.lang][k]||k},refreshIcons(){},toggleLang(){this.lang=this.lang==='zh'?'en':'zh'},goHome(){window.scrollTo({top:0,behavior:'smooth'})},normalizeLocation(v){return String(v||'').trim().replace(/\s+/g,'').replace(/^中华人民共和国|^中國|^中国/,'')},resolveKnownRegion(v){const key=this.normalizeLocation(v);return chinaRegionLookup.get(key)||chinaRegionLookup.get(`中国${key}`)||null},
    async searchCity(){if(this.query.trim().length<2){this.notify(this.lang==='zh'?'请输入至少两个字符':'Enter at least 2 characters');return}const knownRegion=this.resolveKnownRegion(this.query);if(knownRegion){this.suggestions=[];await this.selectCity({...knownRegion},true);return}this.loading=true;this.weatherError='';try{const rawQuery=this.query.trim(),url=`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(rawQuery)}&count=12&language=${this.lang}&format=json`;const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error();const data=await res.json(),normalized=this.normalizeLocation(rawQuery);const seen=new Set();this.suggestions=(data.results||[]).filter(city=>{const key=`${city.name}|${city.country}|${city.admin1||''}|${city.admin2||''}`.toLocaleLowerCase();if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>{const ae=this.normalizeLocation(a.name)===normalized?1:0,be=this.normalizeLocation(b.name)===normalized?1:0;if(ae!==be)return be-ae;return(b.population||0)-(a.population||0)}).slice(0,8);if(this.suggestions.length===1)await this.selectCity(this.suggestions[0],true);else if(this.suggestions.length>1)this.notify(this.t('chooseCity'));else this.notify(this.lang==='zh'?'没有找到这个城市，请换个关键词':'No city found. Try another keyword.')}catch(e){this.weatherError=this.lang==='zh'?'全球城市搜索暂时不可用，请重试':'Global city search is temporarily unavailable';this.notify(this.weatherError)}finally{this.loading=false;this.refreshIcons()}},
    async selectCity(city,shouldScroll=true){const requestId=++this.weatherRequestId;this.selectedCity=city;this.query=city.name;this.suggestions=[];this.weather=null;this.weatherError='';this.itinerary=[];this.attractions=[];this.planError='';this.loading=true;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const p='current=temperature_2m,relative_humidity_2m,apparent_temperature,is_day,weather_code,wind_speed_10m&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max';const url=`https://api.open-meteo.com/v1/forecast?latitude=${city.latitude}&longitude=${city.longitude}&${p}&timezone=auto&forecast_days=7`;const res=await fetch(url,{cache:'no-store',signal:controller.signal});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();if(requestId!==this.weatherRequestId)return;data.source_url=url;this.weather=data;localStorage.setItem('yidan-last-city',JSON.stringify(city));this.loadAttractions(city,data);this.notify(this.lang==='zh'?`已加载 ${city.name}（${city.country}）的天气预报`:`Forecast loaded for ${city.name}, ${city.country}`)}catch(e){if(requestId===this.weatherRequestId){this.weather=null;this.weatherError=this.t('loadFailed');this.notify(this.weatherError)}}finally{clearTimeout(timer);if(requestId===this.weatherRequestId){this.loading=false;this.refreshIcons();if(shouldScroll)nextTick(()=>document.querySelector('#discover')?.scrollIntoView({behavior:'smooth'}))}}},
    async quickSearch(city,shouldScroll=true){if(city&&typeof city==='object'&&Number.isFinite(city.latitude))return this.selectCity(city,shouldScroll);const name=String(city),knownRegion=this.resolveKnownRegion(name);if(knownRegion)return this.selectCity({...knownRegion},shouldScroll);this.query=name;this.loading=true;this.weatherError='';try{const res=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(name)}&count=1&language=${this.lang}&format=json`,{cache:'no-store'});const data=await res.json();if(data.results?.[0])await this.selectCity(data.results[0],shouldScroll);else throw new Error()}catch(e){this.weather=null;this.weatherError=this.t('loadFailed');this.notify(this.weatherError);if(shouldScroll)document.querySelector('#discover')?.scrollIntoView({behavior:'smooth'})}finally{this.loading=false}},
    toggleSave(){if(!this.selectedCity)return;if(!this.user){this.showLogin=true;return}if(this.isSaved)this.savedCities=this.savedCities.filter(c=>c.id!==this.selectedCity.id);else this.savedCities.push(this.selectedCity);localStorage.setItem('yidan-saved',JSON.stringify(this.savedCities));this.notify(this.isSaved?this.t('saved'):(this.lang==='zh'?'已取消收藏':'Removed from saved'))},
    login(){this.user={...this.loginForm};localStorage.setItem('yidan-user',JSON.stringify(this.user));this.showLogin=false;this.notify(this.lang==='zh'?`欢迎，${this.user.name}！`:`Welcome, ${this.user.name}!`)},logout(){localStorage.removeItem('yidan-user');this.user=null;this.showProfile=false},
    async loadAttractions(city,weather=this.weather){this.attractionsLoading=true;this.planError='';this.itinerary=[];const cacheKey=`yidan-attractions-${city.id}-${this.lang}`;try{const cached=JSON.parse(localStorage.getItem(cacheKey)||'null');if(cached&&Date.now()-cached.savedAt<21600000&&cached.items?.length>=3){this.attractions=cached.items;this.generateItinerary(weather);this.attractionsLoading=false;return}}catch(e){}const lat=Number(city.latitude),lon=Number(city.longitude),south=(lat-.08).toFixed(5),north=(lat+.08).toFixed(5),west=(lon-.10).toFixed(5),east=(lon+.10).toFixed(5),box=`${south},${west},${north},${east}`;const query=`[out:json][timeout:15];(nwr["tourism"~"attraction|museum|gallery|viewpoint|aquarium|theme_park"]["name"](${box});nwr["historic"~"monument|memorial|castle|temple|archaeological_site"]["name"](${box});nwr["leisure"="park"]["name"](${box}););out center tags 80;`,endpoints=['https://overpass-api.de/api/interpreter','https://maps.mail.ru/osm/tools/overpass/api/interpreter'];try{let data=null;for(const endpoint of endpoints){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),18000);try{const res=await fetch(endpoint+'?data='+encodeURIComponent(query),{cache:'no-store',signal:controller.signal});if(res.ok){data=await res.json();if(data.elements?.length)break}}catch(e){}finally{clearTimeout(timer)}}if(!data)throw new Error('All Overpass endpoints failed');if(this.selectedCity?.id!==city.id)return;const seen=new Set(),ranked=(data.elements||[]).map(e=>{const t=e.tags||{},name=t[`name:${this.lang}`]||t['name:zh']||t.name||t['name:en'];if(!name)return null;const key=name.toLocaleLowerCase();if(seen.has(key))return null;seen.add(key);const kind=t.tourism||t.historic||t.leisure||'attraction';const indoor=['museum','gallery','aquarium'].includes(kind),point=e.center||e;let score=(t.wikipedia?8:0)+(t.wikidata?5:0)+(t.website?1:0)+(t['name:zh']||t['name:en']?2:0)+(['attraction','viewpoint','castle','temple'].includes(kind)?4:0)+(['museum','gallery','aquarium'].includes(kind)?3:1);return{name,kind,indoor,lat:point.lat,lon:point.lon,score,mapUrl:`https://www.openstreetmap.org/?mlat=${point.lat}&mlon=${point.lon}#map=16/${point.lat}/${point.lon}`}}).filter(p=>p&&Number.isFinite(p.lat)&&Number.isFinite(p.lon)).sort((a,b)=>b.score-a.score);this.attractions=[...ranked.filter(p=>!p.indoor).slice(0,12),...ranked.filter(p=>p.indoor).slice(0,12)];if(this.attractions.length<3)throw new Error('Not enough named attractions');localStorage.setItem(cacheKey,JSON.stringify({savedAt:Date.now(),items:this.attractions}));this.generateItinerary(weather)}catch(e){this.planError=this.t('planFailed');this.itinerary=[]}finally{this.attractionsLoading=false}},
    attractionLabel(kind){const zh={museum:'博物馆',gallery:'美术馆',viewpoint:'观景台',zoo:'动物园',aquarium:'水族馆',theme_park:'主题乐园',park:'城市公园',memorial:'历史纪念地',monument:'历史地标',castle:'城堡',temple:'寺庙',shrine:'神社',attraction:'人气景点'};const en={museum:'Museum',gallery:'Gallery',viewpoint:'Viewpoint',zoo:'Zoo',aquarium:'Aquarium',theme_park:'Theme park',park:'Park',memorial:'Memorial',monument:'Historic landmark',castle:'Castle',temple:'Temple',shrine:'Shrine',attraction:'Attraction'};return(this.lang==='zh'?zh:en)[kind]||(this.lang==='zh'?'当地景点':'Local attraction')},
    generateItinerary(weather=this.weather){if(!weather||!this.attractions.length)return;const indoor=this.attractions.filter(p=>p.indoor),outdoor=this.attractions.filter(p=>!p.indoor),used=new Set(),pick=(list,fallback)=>{const p=list.find(x=>!used.has(x.name))||fallback.find(x=>!used.has(x.name));if(p)used.add(p.name);return p};const plan=[];for(let day=0;day<3;day++){const rain=weather.daily.precipitation_probability_max[day]||0,max=Math.round(weather.daily.temperature_2m_max[day]),code=weather.daily.weather_code[day],rainy=rain>=50;for(let slot=0;slot<2;slot++){const place=pick(rainy?(slot===0?indoor:outdoor):outdoor,this.attractions);if(!place)continue;const reasonZh=rainy?(place.indoor?`降水概率 ${rain}%，优先安排室内参观`:`建议趁雨势较小时前往`):(place.indoor?(max>=30?'午后炎热，转入室内舒适参观':'穿插室内文化体验，平衡步行强度'):(max>=30&&slot===1?'避开正午高温，安排在下午较晚时段':`天气适合户外探索，最高 ${max}°`));const reasonEn=rainy?(place.indoor?`${rain}% rain chance—ideal for an indoor visit`:'Visit during a lighter rain window'):(place.indoor?(max>=30?'Escape the afternoon heat with an indoor visit':'An indoor cultural stop balances the walking'):(max>=30&&slot===1?'Avoiding midday heat with a later visit':`Good for exploring outdoors, high ${max}°`));plan.push({day:day+1,time:slot===0?'09:30':'15:00',icon:place.indoor?'landmark':'camera',zh:place.name,en:place.name,descZh:`${this.attractionLabel(place.kind)} · ${reasonZh}`,descEn:`${this.attractionLabel(place.kind)} · ${reasonEn}`,forecast:`${this.weatherIcon(code)} ${max}° · ☂ ${rain}%`,mapUrl:place.mapUrl})}}this.itinerary=plan;this.notify(this.lang==='zh'?`已根据天气生成 ${plan.length} 个真实景点行程`:`Generated ${plan.length} real attractions for the forecast`)},
    addActivity(){this.generateItinerary()},removeActivity(i){this.itinerary.splice(i,1)},
    weatherIcon(c){if(c===0)return'☀️';if(c<=3)return'⛅';if(c<=48)return'🌫️';if(c<=67)return'🌧️';if(c<=77)return'🌨️';if(c<=82)return'🌦️';return'⛈️'},weatherText(c){const zh=c===0?'晴朗':c<=3?'多云':c<=48?'有雾':c<=67?'有雨':c<=77?'有雪':c<=82?'阵雨':'雷雨';const en=c===0?'Clear':c<=3?'Cloudy':c<=48?'Foggy':c<=67?'Rainy':c<=77?'Snowy':c<=82?'Showers':'Stormy';return this.lang==='zh'?zh:en},
    formatDate(d){return new Intl.DateTimeFormat(this.lang==='zh'?'zh-CN':'en-US',{month:'long',day:'numeric',weekday:'long'}).format(new Date(d))},formatTime(d){return new Intl.DateTimeFormat(this.lang==='zh'?'zh-CN':'en-US',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:this.weather?.timezone||undefined}).format(new Date(d))},dayName(d){return new Intl.DateTimeFormat(this.lang==='zh'?'zh-CN':'en-US',{weekday:'short'}).format(new Date(d))},notify(msg){this.toast=msg;this.refreshIcons();setTimeout(()=>this.toast='',2600)}
  }
}).mount('#app');
